### ISSUE TITLE
Simplify Bit Rate and Allow App to Record In More Audio Formats

### ISSUE THREAD

**Issue by autofreak** [Dimowner/AudioRecorder#17]
Change the rate to something like low, lower, medium, high and higher. These can be easily understood by many users. Some people don't know what 48000Hz is.

I understand the need for uncompressed audio formats like WAV, but I suggest that you include lossy audio formats like MP3 in subsequent updates since it is the most popular one in the music world.

**Comment by ucasiggcas** [comment]
and could it be pcm version ?

**Comment by Dimowner** [comment]
Adding MP3 format is a quite complicated task. I am looking for it. But it pussibly will break the main idea of this application "Very small and functional app" Because MP3 format needs using of some libraries which will increase app size few times. WAV format already supported.

"and could it be pcm version ?" Please specify what exactly do you mean when writing PCM

**Comment by PontiacCZ** [comment]
I am actually for keeping the sample rate (Hz) and bitrate as it is because one knows exactly what it means. Those who don't at least understand that more is better and less is worse, just like with "high" or "low".

**Comment by Dimowner** [comment]
(Hz) will remain. But I am working on app settings improvements and "low", "high" "recommended" will be added as additional information.
