### ISSUE TITLE
Please add saving to public folder feature to Android 10 and older OSes

### ISSUE THREAD

**Issue by TamasSzerb** [Dimowner/AudioRecorder#54]
This feature cannot be turned on on Current Version 0.9.7

**Comment by mmoole** [comment]
Yes! It's also like this at version 0.9.14 - and I was really surprised by this difference in functions.
That would be totally great, because the current folder cannot be read by some backup applications.
When saving recordings directly on the internal card (and not in any special folder), that would make it easier to be included in backup and sync apps... and be used after the recording for the next steps.

**Comment by xeruf** [comment]
Why only Android 10 and older?
I run Lineage 18 (equivalent to Android 11) and I cannot change the folder either, and would very much like to :/

**Comment by xeruf** [comment]
Ah see https://github.com/Dimowner/AudioRecorder/releases/tag/0.9.14, oof

**Comment by Dimowner** [comment]
There is no plans to add feature where user can change recording directory. Newer versions of Android added restrictions on ability to interact with device file system. There is no simple way how to implement the feature. So all records are stored in app's private dir. Anyway, all record files available for user to download from app's private dir to a public dir.
