### ISSUE TITLE
Copycat on Google Play

### ISSUE THREAD

**Issue by Poussinou** [Dimowner/AudioRecorder#63]
Hi,

I found this copy of your app on Google Play below, just to let you know.

https://play.google.com/store/apps/details?id=com.sain.recorder from [this developer](https://play.google.com/store/apps/developer?id=Appntox)

Maybe you could send a DMCA request to Google if you want it ;)

**Comment by Poussinou** [comment]
Another one here : https://play.google.com/store/apps/details?id=com.sladjan.audiorecorder from [this developer](https://play.google.com/store/apps/developer?id=Sladjan).

**Comment by chemputer** [comment]
Looking at the Apache license used, this would technically be allowed, _if_ they included the license in the app. They don't. So, yeah, contact Google. 

I'd change your license, so that someone can't use it for commercial gain without modifying it and definitely can't publish it on Google Play without your permission. 

I'm all for open source software, but this is just a free app getting stolen, the icon changed, and sold for $3 or so and getting sales, which is messed up.

**Comment by Poussinou** [comment]
Another one here https://play.google.com/store/apps/details?id=com.chexsound.audiorecorder from this developer https://play.google.com/store/apps/dev?id=6130128057652620670

**Comment by chemputer** [comment]
Hey @Poussinou you've contributed to the app, so you have some ground to ask google to take down these apps. 

The saddest/funniest part depending on whether you want to laugh or cry is they don't even bother to add the license to make it legal, they don't even bother to change the EMAIL within the app for feature requests/feedback, but they do change the app that's linked to for the "rate app", if that's not just automatically pulling the package's ID to get the app link. How freaking lazy. If someone requests a feature, it goes to @Dimowner and he might implement the feature, then the leech just uploads the new version to the Play Store and gets good reviews. How is this okay? 

![ChexAppAudioRecorderSS_edited](https://user-images.githubusercontent.com/46601333/226709251-a0a20f49-9e80-4798-a8b7-f93a959d643b.png)

**Comment by Mennaruuk** [comment]
Maybe it's time to change the license to something like GPL. This is one reason the web browser [Vivaldi](https://vivaldi.com/blog/vivaldi-browser-open-source/) hasn't gone 100% open source:

>The new product then becomes an immediate competitor without putting any significant technical work to reach that status (it would still need to be marketed though).

**Comment by Dimowner** [comment]
Thanks for attention to these copy cat apps. I quite often receive emails from copy cat apps users who use 'Request or feedback' form there, because of copy cat app devs didn't change contact email. I anticipate there are many more Audio Recorder copy cat apps. I don't really care about them. 

I am not going to try to report and remove them from Google Play Market. It takes too much time and efforts. 

I am not going to change the Licence. 

If I decide to make paid a version of the Audio Recorder with extended functionality, I just won't publish it on Github public repo. Anything else published here is free to use, except app Logo and branding.

Regarding CI/CD I may setup some Github actions to run unit tests and perform code quality checks. Not sure about automated releases.
